#!/bin/bash

# Portfolio Deployment Setup Script
echo "🚀 Setting up Salah's Portfolio for Deployment..."

echo "📋 Pre-deployment Checklist:"
echo "✅ Updated package.json with start scripts"
echo "✅ Added environment port configuration"
echo "✅ Created .gitignore files"
echo "✅ Created requirements.txt for Python app"

echo ""
echo "🌐 Recommended Hosting Strategy:"
echo ""
echo "1️⃣  MAIN PORTFOLIO (Node.js/Express)"
echo "   Platform: Render.com (Free)"
echo "   URL: https://salah-portfolio.onrender.com"
echo "   Steps:"
echo "   - Create GitHub repo: 'salah-portfolio'"
echo "   - Connect to Render"
echo "   - Set build command: npm install"
echo "   - Set start command: npm start"
echo ""

echo "2️⃣  BLOG PROJECT (Node.js API)"
echo "   Platform: Render.com (Free)"
echo "   URL: https://salah-blog-api.onrender.com"
echo "   Steps:"
echo "   - Create GitHub repo: 'salah-blog-api'"
echo "   - Connect to Render"
echo "   - Set start command: npm start"
echo ""

echo "3️⃣  E-COMMERCE FRONTEND (React/Vite)"
echo "   Platform: Vercel.com (Free)"
echo "   URL: https://salahmart.vercel.app"
echo "   Steps:"
echo "   - Create GitHub repo: 'salahmart-frontend'"
echo "   - Connect to Vercel"
echo "   - Build command: npm run build"
echo "   - Output directory: dist"
echo ""

echo "4️⃣  E-COMMERCE BACKEND (Node.js API)"
echo "   Platform: Render.com (Free)"
echo "   URL: https://salahmart-api.onrender.com"
echo "   Steps:"
echo "   - Create GitHub repo: 'salahmart-backend'"
echo "   - Extract server.js to separate project"
echo "   - Connect to Render"
echo ""

echo "5️⃣  WEATHER APP (Python/Streamlit)"
echo "   Platform: Streamlit Community Cloud (Free)"
echo "   URL: https://salah-weather-app.streamlit.app"
echo "   Steps:"
echo "   - Create GitHub repo: 'salah-weather-app'"
echo "   - Connect to Streamlit Cloud"
echo "   - Main file: app.py"
echo ""

echo "📝 Next Steps:"
echo "1. Create GitHub repositories for each project"
echo "2. Push code to respective repositories"
echo "3. Set up hosting accounts (Render, Vercel, Streamlit)"
echo "4. Deploy each project"
echo "5. Update portfolio links with production URLs"
echo ""

echo "🔗 After deployment, update these URLs in your portfolio:"
echo "- Blog Project: Update in views/index.ejs"
echo "- E-commerce: Update in views/index.ejs"
echo "- Weather App: Update in views/index.ejs"
echo "- API Endpoints: Update in E-commerce frontend"
echo ""

echo "💡 Tips:"
echo "- Render apps sleep after 15 minutes of inactivity (cold start)"
echo "- Keep one tab open to each app to prevent sleeping"
echo "- Vercel is instant for static React apps"
echo "- Streamlit Community Cloud is perfect for Python demos"
echo ""

echo "🎉 Your portfolio is ready for deployment!"
echo "Would you like help with any specific deployment step?"